### ISSUE TITLE
Duplicate output in iOS build

### ISSUE THREAD

**Issue by cmehmet-tomp** [moeddami/nativescript-vue-global-drawer#1]
Hi . Thank you for the hard work and excellent plugin . 

I'm currently having a problem with iOS build which I think it's related to node_modules inside your plugin . 

The errors I'm getting : 

`warning: duplicate output file 'my_app/platforms/ios/build/Debug-iphonesimulator/myapp.app/Frameworks/TNSSideDrawer.framework' on task: PBXCp my_app/node_modules/nativescript-vue-global-drawer/node_modules/nativescript-ui-sidedrawer/platforms/ios/TNSSideDrawer.framework my_app/platforms/ios/build/Debug-iphonesimulator/myapp.app/Frameworks/TNSSideDrawer.framework (in target 'myapp')
warning: duplicate output file '' on task: PBXCp my_app/node_modules/nativescript-vue-global-drawer/node_modules/nativescript-ui-sidedrawer/platforms/ios/TNSSideDrawer.framework my_app/platforms/ios/build/Debug-iphonesimulator/myapp.app/Frameworks/TNSSideDrawer.framework (in target 'myapp')
error: Multiple commands produce 'my_app/platforms/ios/build/Debug-iphonesimulator/myapp.app/Frameworks/TNSSideDrawer.framework':

1) Target 'myapp' (project 'myapp') has copy command from 'my_app/node_modules/nativescript-ui-sidedrawer/platforms/ios/TNSSideDrawer.framework' to 'my_app/platforms/ios/build/Debug-iphonesimulator/myapp.app/Frameworks/TNSSideDrawer.framework'
2) Target 'myapp' (project 'myapp') has copy command from 'my_app/node_modules/nativescript-vue-global-drawer/node_modules/nativescript-ui-sidedrawer/platforms/ios/TNSSideDrawer.framework' to 'my_app/platforms/ios/build/Debug-iphonesimulator/myapp.app/Frameworks/TNSSideDrawer.framework'
error: Multiple commands produce '<PbxCp my_app/platforms/ios/build/Debug-iphonesimulator/myapp.app/Frameworks/TNSSideDrawer.framework>':
1) Target 'myapp' (project 'myapp') has copy command from 'my_app/node_modules/nativescript-ui-sidedrawer/platforms/ios/TNSSideDrawer.framework' to 'my_app/platforms/ios/build/Debug-iphonesimulator/myapp.app/Frameworks/TNSSideDrawer.framework'
2) Target 'myapp' (project 'myapp') has copy command from 'my_app/node_modules/nativescript-vue-global-drawer/node_modules/nativescript-ui-sidedrawer/platforms/ios/TNSSideDrawer.framework' to 'my_app/platforms/ios/build/Debug-iphonesimulator/myapp.app/Frameworks/TNSSideDrawer.framework'
note: Using new build systemnote: Planning buildnote: Constructing build description
':

I don't have a problem in Android though. 

My nodejs version : v10.15.3
npm version : 6.4.1
yarn version : 1.16.0
Nativescript version - 5.3.4

`

**Comment by moeddami** [comment]
Yes it's related to plugin dependencies. I will fix it soon as possible.
