### ISSUE TITLE
I am having an issue rendering components within the global drawer. 

### ISSUE THREAD

**Issue by Syltis** [moeddami/nativescript-vue-global-drawer#3]
I'm trying to render components using the buttons in the sideDrawer. Not absolutely sure if it's an issue with the plugin, something with NS-vue in general, or my own fault. I posted an explanation on SO if you wanna have a look:

https://stackoverflow.com/questions/57491485/how-to-fix-blank-screen-when-trying-to-render-components-with-is-component

Great plugin btw, would love to fix this and use it permanently.

**Comment by hgc2002** [comment]
I'm in the same issue but unfortunately the explanation of @Syltis in stackoverflow is still vague. It should include some kind of example much easier to follow. I really appreciate if anybody can help in this direction.

**Comment by moeddami** [comment]
Please see my answer: https://stackoverflow.com/a/59812072/7306766
